name: yago-web
services:
  blazegraph:
    container_name: blazegraph
    ports:
      - 8889:8080
    image: lyrasis/blazegraph:2.1.5
    volumes:
      - ./data:/data
      - ./RWStore.properties:/RWStore.properties
    environment:
      - BLAZEGRAPH_UID=${UID:-1000} # Use current user's UID or default to 1000
      - BLAZEGRAPH_GID=${GID:-1000} # Use current user's GID or default to 1000
      - JAVA_OPTS=${JAVA_OPTS}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8889"]
      interval: 3s
      timeout: 5s
      retries: 3

  php-server:
    container_name: php-server
    ports:
      - 8080:80
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 3s
      timeout: 5s
      retries: 3
